name: Deploy Your landing page to Goggle App Engine (GAE) ğŸ¥³

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      RANDOM: production
    steps:
      - name: Checkout repository ğŸ¥¸
        uses: actions/checkout@v2

      - name: Setup Node.js and yarn ğŸ
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies ğŸ˜
        run: npm install --legacy-peer-deps --frozen-lockfile

      - name: Build Nextjs Project ğŸš€
        run: npm run google-build

      - name: GCP Build dynamic routes ğŸ› ï¸
        run: npm run gcp-build

      - name: Google Cloud Auth ğŸª„
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_PROD_KEY }}'
          project_id: ${{ secrets.GCP_PROD_PROJECT_ID }}

      - name: Set up Cloud SDK ğŸ«†
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Google App Engine ğŸ‘‘
        run: |
          npm run gcp-predeploy && gcloud app deploy app.yaml
